version: '3.1'
services:
    postgresql:
        build:
            context: ./postgresql
        networks:
            - spring-boot-multiple-database
    mysql:
        build:
            context: ./mysql
        networks:
            - spring-boot-multiple-database
    app:
        build:
            context: ./app
        ports:
            - 8081:8080
        networks:
            - spring-boot-multiple-database  
        depends_on:
            - postgresql
            - mysql
networks:
    spring-boot-multiple-database: